name: env_test
channels:
  - conda-forge
dependencies:
  - matplotlib=3.7.1
  - numpy=1.25.0
  - pandas=2.0.2
  - pip=23.1.2
  - plotly=5.15.0
  - python=3.9.16
  - simpy=4.0.1
  - Pillow=9.5.0
  - pip:
    - streamlit==1.24.0
    - reportlab==4.0.6
